[package]
name = "tarfs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.70"
bzip2 = "0.4.4"
clap = { version = "4.2.1", features = ["derive"] }
flate2 = "1.0.25"
fork = "0.1.21"
fuser = "0.12.0"
libc = "0.2.140"
tar = "0.4.38"
users = "0.11.0"
xz2 = "0.1.7"
zstd = "0.12.3"
